#!/bin/bash
ORNG='\033[0;33m'
NC='\033[0m'
W='\033[1;37m'
LP='\033[1;35m'
YLW='\033[1;33m'
LBBLUE='\e[104m'
# Exploitation
# Metepreter payload
dropper_mods(){
    if [[ -d '/opt/TigerShark/Payloads' ]]; then
        sleep 1
    else
        mkdir /opt/TigerShark/Payloads
    fi
    PS3='How would you like to create your payload?'
        options=("Enigma" "html Server Gateway" "Pupy" "RCE VBS Exploit" "Back") 
        select opt in "${options[@]}"
        do
            case $opt in
                "Enigma")
                    ./Modules/Droppers/enigma.sh
                    ;;

                "html Server Gateway(Edge 11 vb RCE)")
                    ./Modules/Droppers/ie_vb.sh
                    ;;
                
                "Pupy")
                    ./Modules/Droppers/pupy.sh
                    ;;

                "Phantom-Evasion")
                    ./Modules/Droppers/phantom.sh
                    ;;
                    
                "RCE VBS Exploit")
                    ./Modules/Droppers/vbs_rce.sh
                    ;;

                "Back")
                    ./tigershark
                    ;;
            esac
        done
}
# Recon Modules
# Gathering Module Selector
gathering_mods(){
    PS3='Please define your activity?'
        options=("Gathering Potential eMail targets for Campaign" "Gathering Potential Domains for Campaign") 
        select opt in "${options[@]}"
        do
            case $opt in
                "Gathering Potential eMail targets for Campaign")
                    email_collection
                    ;;

                "Gathering Potential Domains for Campaign")
                    domain_collection
                    ;;
                              
            esac
        done    
}
# Email Collection Modules
email_collection(){
   PS3='Please select the tool for email gathering'
        options=("PhishBait" "EmailGen" "PhEmail" "Back") 
        select opt in "${options[@]}"
        do
            case $opt in
                "PhishBait")
                    ./Modules/Gathering/Email/phishbait.sh
                    ;;

                "EmailGen")
                    ./Modules/Gathering/Email/egen.sh
                    ;;

                "PhEmail")
                    ./Modules/Gathering/Email/phemail.sh
                    ;;

                "Back")
                    ./tigershark
                    ;;   
            esac
        done 
}
# Domain Collection Modules
domain_collection(){
    PS3='Please select the tool for domain gathering'
        options=("CatPhish" "DomainHunter" "Back") 
        select opt in "${options[@]}"
        do
            case $opt in
                "CatPhish")
                    ./Modules/Gathering/Domain/catphish.sh
                    ;;
             
                "DomainHunter")
                    ./Modules/Gathering/Domain/domainhunter.sh
		            ;;

                "Back")
                    ./tigershark
                    ;;
            esac
        done
}

# Phishing Modules 
# Exploitation Module Selector
phishing_mods(){
    PS3='What would you like to do?'
        options=("Create a Single-Page Phishing Site" "Create a Multi-Page/Phishing Campaign" "Spam Phishing Mail" "Back") 
        select opt in "${options[@]}"
        do
            case $opt in
                "Create a Single-Page Phishing Site")
                    single_pole
                    ;;

                "Create a Multi-Page/Phishing Campaign")
                    trawler
                    ;;

                "Spam Phishing Mail")
                    spammer
                    ;;

                "Back")
                    ./tigershark
                    ;;                   
            esac
        done
}
# Single-Page Tools
single_pole(){
    PS3='Please Select Your Tool for Single-Page Phisher Generation'        
        options=("Artemis" "HiddenEye" "PhishX" "WeeMan" "CredSniper" "Back") 
        select opt in "${options[@]}"
        do
            case $opt in
                "Artemis")
                    ./Modules/Phishing/Singular/artemis.sh
                    ;;
             
                "HiddenEye")
                    ./Modules/Phishing/Singular/hiddeneye.sh
                    ;;

                "PhishX")
                    ./Modules/Phishing/Singular/phishx.sh
                    ;;
                
                "WeeMan")
                    ./Modules/Phishing/Singular/weeman.sh
                    ;;

                "CredSniper")
                    ./Modules/Phishing/Singular/credsniper.sh
                    ;;

                "Back")
                    ./tigershark
                    ;;

            esac
        done
}
# Multi-Page Tools
trawler(){
    PS3='Please Select Your Tool for Campaign Phisher Generation'        
    options=("GoPhish" "SocialFish" "STP" "Back") 
        select opt in "${options[@]}"
        do
            case $opt in
                "GoPhish")
                    ./Modules/Phishing/Trawler/gophish.sh
                    ;;
             
                "SocialFish")
                    ./Modules/Phishing/Trawler/socialfish.sh
                    ;;

                "STP")
                    ./Modules/Phishing/Trawler/stp.sh
                    ;;

                "Back")
                    ./tigershark
                    ;;
            esac
        done
}
# Phishing Mail Spamming Tools
spammer(){
    PS3='Please Select Your Tool for Mail Spamming'        
    options=("PhEmail" "Neos-Mail Spoofer" "Back") 
        select opt in "${options[@]}"
        do
            case $opt in
                "PhEmail")
                    ./Modules/Baiting/phemail.sh
                    ;;

                "Neos-Mail Spoofer")
                    ./Modules/Baiting/neos.sh
                    ;;

                "Back")
                    ./tigershark
                    ;;
            esac
        done
}


# Start of TigerShark
cd /opt/TigerShark
echo -e "${LP}"
cat .vs/1
echo -e "${ORNG}"
figlet -f small "s1l3nt78"
echo -e "${NC}"
if [[ -d '/opt/TigerShark/Results' ]]; then 
    sleep 1
else 
    mkdir /opt/TigerShark/Results
fi
PS3='What would you like to do?'
        options=("Perform Recon" "Deploy Fishing Environment" "Create a Payload" "Update") 
        select opt in "${options[@]}"
        do
            case $opt in
                "Perform Recon")
                    gathering_mods
                    ;;

                "Deploy Fishing Environment")
                    phishing_mods
                    ;;

                "Create a Payload")
                    dropper_mods
                    ;;

                "Update")
                    echo -e "${ORNG}"
                    figlet -f mini "Checking for updates"
                    echo -e "${NC}"
                    cd /opt/TigerShark
                    git fetch
                    git pull
                    ./install.sh
                    chmod +x Modules --recursive
                    ./tigershark
		            ;;

            esac
        done
